### PR TITLE
Create Agency page

### LINKED ISSUE #564: Agency page
Agency-facing page on website as subpage under "Projects" tab

@jaredbain  If we had a Google Doc of content for a new page (call it /agencies...?), how long would it take to spin it up, including any design? We'd probably keep it fairly barebones design-wise.

### PR DESCRIPTION
**Pull request by jaredbain**
Fixes #564

## Checklist

- [ ] My code follows the existing style, code structure, and naming taxonomy
- [ ] I have performed a self-review of my own code and have no open issues
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or syntax errors
- [ ] I have verified Draft on actual mobile devices, especially Safari-based

### CODE REVIEW

**Comment by chriskuang4** [comment]
- [ ] Include a deadline somewhere to submit (Dec 13)
- [ ] Figure out line spacing between bullets (more condensed than rest of page)
- [ ] Change header to `Project and impact areas`. Link here to our project page too somehow. 
- [ ] Change header to `USDC partnership process`
- [ ] Don't need to capitalize interagency agreements. Use `Interagency agreements` in first mention, then interagency agreement lowercase. Also change text to `Fellows are hired at GSA`. Also lowercase IAA in "timeline of major milestones"
- [ ] The blue bold text in the partnership section -- do we have that color anywhere else on the website? 
- [ ] Sentence case the bold parts of the bullets in agency participation criteria + project priorities (e.g. "Impact-driven projects")
- [ ] Change "skilled in fields like" to "specializing in" in the How it works section. We may need to also change the "join your team" verbiage for OGC. 

- [ ] Agree w/ Emily that we need to/should run by OGC. I can do this once the staging link is updated.
-

**Comment by ehcarter** [comment]
- [ ] Propose changing the IAA bullet to say "Interagency Agreements (IAA): Fellows are hired through GSA to GS-9/11/12 career ladder positions. Fellows provide technical services to agencies via interagency service agreements, spending 80-90% of their time on agency work, with the balance on cohort learning and development. Our standard agreements are severable, reimbursable service agreements."
- [ ] Suggest removing the Pathways to Conversion bullet from "Agency Participation criteria"
- [ ] Suggest changing the second sentence to say "As recent graduates, Fellows bring expertise in the latest cutting edge technologies, methodologies, and best practices. USDC provides a dedicated learning and development program throughout the two year fellowship, ensuring Fellows have the technical and leadership skills needed to serve your team. USDC is designed to allow agencies to easily convert Fellows to permanent positions at the end of the fellowship, where Fellows can continue their public service journey within teams or projects where they have made impactful contributions."

**Comment by jaredbain** [comment]
Completed all the edits for the agency page

**Comment by Dahianna** [comment]
@chriskuang4 hey do we still need to run this by OGC? If so, let me know and I can share with Katie.

**Comment by Dahianna** [comment]
Feedback from OGC was implemented on Nov 26

**Comment by jaredbain** [comment]
Code updates look good

**Review by chriskuang4 — APPROVED** [review]

**Pull request merged**
