### PR TITLE
Replace stock images

### LINKED ISSUE #191: Replace stock photos with orientation photos
- [ ] @danielaaburtotc is formatting photos (4 remaining to send to Jared)
- [ ] @Dahianna to get Fellow approvals (anything outside whole group shots)
- [ ] @jaredbain to add to website

[Spreadsheet with photos and locations](https://docs.google.com/spreadsheets/d/1Rf86AnTCFb7EWADJpgTS32caObzrk6zYaR-pJQV9hZk/edit#gid=0)

Estimated Completion: 1 day

### PR DESCRIPTION
**Pull request by jaredbain**
Replace stock images on website with USDC photos of fellows

Fixes #191 

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and have no open issues
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or syntax errors
- [x] I have verified Draft on actual mobile devices, especially Safari-based

### CODE REVIEW

**Comment by jaredbain** [comment]
@Dahianna I updated the preview image, just need the PR to get approved and I'll go ahead and push the update.

**Comment by chriskuang4** [comment]
@jaredbain can you mark this as ready for review? Dahianna is out today, I can try to get to it today so we can merge!

**Comment by jaredbain** [comment]
Hey @chriskuang4 , Thanks!! it's been marked as ready now

**Review by chriskuang4 — APPROVED** [review]
Thanks @jaredbain and sorry for the delay! Approved - let's ship.

**Comment by chriskuang4** [comment]
@jaredbain to add the two updated ones, merge live, and then create a new issue/card for the one outstanding photo that's pending

**Pull request merged**
