### PR TITLE
Updating process page with application date, deadline

### PR DESCRIPTION
**Pull request by chriskuang4**

### CODE REVIEW

**Review by DaveSkender — APPROVED** [review]
There’s a small banner image sizing problem in tablet screen size with the extra text length.  I’m taking a note to fix before we publish.

**Comment by chriskuang4** [comment]
Looks like something got funky at the bottom where it says "see FAQs." I don't see that on the current site or in the changes here...

**Comment by DaveSkender** [comment]
The one at the very end only shows in smaller screens when the side menu is hidden.  Can make it always on if that’s better

**Comment by chriskuang4** [comment]
> The one at the very end only shows in smaller screens when the side menu is hidden. Can make it always on if that’s better

Ah. That's what I get for trying to do this all on my laptop.

**Pull request merged**
