### PR TITLE
New blog page

### LINKED ISSUE #84: Add Blog functionality to website
Blog to showcase content from USDC Fellows and leadership [guided by this proposal](https://docs.google.com/document/d/1b5nF3fOohypg4Zz3eBGkCUvujBexoyDCoJW0gYoIvBg/edit)

### PR DESCRIPTION
**Pull request by jaredbain**
Fixes #84 

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and have no open issues
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or syntax errors
- [x] I have verified Draft on actual mobile devices, especially Safari-based

### CODE REVIEW

**Comment by chriskuang4** [comment]
- [ ] add date under author name & above tags
- [ ] Move images to left and above the name
- [ ] Make blog titles H1
- [ ] Dahianna adding "This post was originally published on the [BLOG NAME], [If author is outside GSA NAME] is a [TITLE] at [Agency]"
- [ ] Round tags
- [ ] Chris to write blurbs and tags
- [ ] Order blog posts from most recent at the beginning
- [ ] Daniela will have blog headers by EOW  
- [ ] Remove tag filter on main page
- [ ] Add styling/header to the main blog page
- [ ] Cross-reference loaded in blogs against our spreadsheet 
- [ ] For V1.5 - make tags clickable to load a filtered list of posts with that tag

**Comment by chriskuang4** [comment]
- [ ] remove leading zero from date
- [ ] standarize bylines
- [ ] Remove carousel of news articles

**Comment by chriskuang4** [comment]
A few more updates:
- [ ] Dahianna - Load in 4 (?) press releases (announcing program, announcing first + second cohort, first annivarsary of first cohort)
- [ ] Make tags not clickable in card format
- [ ] General banner for blog home page
- [ ] Fix image sizing on the most recent blog post

**Comment by chriskuang4** [comment]
- [ ] Add styling/header to the main blog page @jaredbain
- [ ]  Impact stories posted
- [ ]  For V1.5 - make tags clickable to load a filtered list of posts with that tag
- [ ]  Dahianna - Load in 4 (?) press releases (announcing program, announcing first + second cohort, first annivarsary of first cohort)
- [ ]  Make tags not clickable in card format
- [ ]  General banner for blog home page
- [ ]  Fix image sizing on the most recent blog post
- [ ] confirm URL is digitalcorps.gsa.gov/blog

**Comment by Dahianna** [comment]
@jaredbain I've added the group photo to the body of https://github.com/GSA/digitalcorps.gsa.gov/blob/new_blog_page/_blogs/celebrating-usdc-second-anniversary-with-new-impact-stories.md

**Comment by jaredbain** [comment]
Fixed extra spacing between fellow images on impact story page

**Review by Dahianna — APPROVED** [review]

**Pull request merged**
