### PR TITLE
Remove more details sentence on projects page

### PR DESCRIPTION
**Pull request by jaredbain**
Remove more details sentence on projects page

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and have no open issues
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or syntax errors
- [x] I have verified Draft on actual mobile devices, especially Safari-based

### CODE REVIEW

**Review by chriskuang4 — APPROVED** [review]
thanks!

**Comment by jaredbain** [comment]
@chriskuang4 Yup I can definitely do that

**Comment by jaredbain** [comment]
@chriskuang4 Let me know if it looks good now

**Comment by chriskuang4** [comment]
Looks great — thanks! Let's ship.

**Pull request merged**
