### PR TITLE
Excludes article files from build

### LINKED ISSUE #198: Google search results lead to unformatted version of press page
## Describe the bug

A google search of "susan rice us digital corps" leads to this site on the first result, https://digitalcorps.gsa.gov/articles/article4/, which is unformatted. 

## Expected behavior
Not sure what's the best path forward -- I like how it's showing up in SEO, but not sure what the page should load.

## Screenshots or other reference materials
Screen Shot 2022-09-13 at 12 07 14 PM

### PR DESCRIPTION
**Pull request by jaredbain**
Excludes article files from build which will prevent them from being searchable on google.

Fixes #198 

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and have no open issues
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or syntax errors
- [x] I have verified Draft on actual mobile devices, especially Safari-based

### CODE REVIEW

**Comment by jaredbain** [comment]
@DaveSkender Hey Dave, I added the article files to the exclude list in config.yml as suggested. Can you take a look a see if everything is correct? thanks!

**Comment by DaveSkender** [comment]
I have two options for recommendations here:

1. Create a nice page layout for articles (as separate pages also, not just cards)
2. Refactor configuration to a simpler fix (instead of having to exclude every new article in the future)

### Create nice page layout

If you look at [Google search results](https://www.google.com/search?q=rice+site%3Adigitalcorps.gsa.gov) currently (bug), you'll see it's indexed on both the landing page and an unformatted published page.

image

What's nice about this is that it may help drive organic traffic to the site; however, you'd just need to have that article page look nice and add a more palatable `permalink` URL to each article markdown file.  If we remove the page, that extra search "hit" with article information will not be shown.  I recommend this approach from a SEO perspective.

### Refactor configuration

Instead of adding individual pages to the `exclude` section of `_config.yml`, which would require someone to remember to do this every time an article is added, try to just change this one variable to `false`.  That would cover all current and future articles.

image

**Comment by jaredbain** [comment]
@DaveSkender Ahhhh okay, yeah that makes sense. And like you said, it'll take care of future articles when added.

**Comment by DaveSkender** [comment]
> @DaveSkender Ahhhh okay, yeah that makes sense. And like you said, it'll take care of future articles when added.

Yah, normally folders with `_` prefix are excluded, but the config file is explicitly telling it to output as a collection of pages, like `_fellows` pages.

**Review by DaveSkender — APPROVED** [review]
Looks good for option 2.  Suggest the other page option to the team also (even if considered for later); I think there's some real SEO benefits to it.

**Comment by jaredbain** [comment]
@DaveSkender I agree. It's definitely something to look into for the future. Thanks Dave!

**Pull request merged**
