### PR TITLE
Updates nav bar to dropdown menu

### LINKED ISSUE #237: Fix nav bar spacing for medium width screens
When screen size is between tablet and desktop size, the nav bar gets compacted and is not visually appealing.

### PR DESCRIPTION
**Pull request by jaredbain**
Updates navigation bar to dropdown nav bar

Fixes #237 

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and have no open issues
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or syntax errors
- [x] I have verified Draft on actual mobile devices, especially Safari-based

### CODE REVIEW

**Comment by jaredbain** [comment]
Nav dropdown added. Still working on styling for it.

**Comment by jaredbain** [comment]
Styling added to new dropdown menu

**Comment by jaredbain** [comment]
@chriskuang4 @Dahianna Just need one approval for the PR and I'll go ahead and merge it to the site. As discussed in the standup, I'll create a bug ticket for the sublink hover feature

**Comment by Dahianna** [comment]
@jaredbain ready to merge

**Pull request merged**
