### PR TITLE
Scrub web copy of evergreen language

### LINKED ISSUE #92: Scrub web copy of evergreen language
No longer a new program. Rework language

### PR DESCRIPTION
**Pull request by jaredbain**
## Description

Updated evergreen language of web pages. 

Fixes #92

### CODE REVIEW

**Comment by DaveSkender** [comment]
@jaredbain, I see some issues here in the diff files that indicate that you may not be managing new feature branches optimally.  I can show you some tips so your "files changed" information only shows new stuff (and not the webP stuff as you see here).

**Review by mvdanilova — APPROVED** [review]

**Review by Dahianna — CHANGES_REQUESTED** [review]
On line 91 we say June 2022 cohort and on line 155 we say 2021 application cycle. I think we should be  consistent with wording. I recommend using 2021 application cycle. Other than that it looks good!

**Comment by jaredbain** [comment]
@CaitlinGandhi Any thoughts on the above recommendation from @Dahianna?

**Comment by jaredbain** [comment]
@Dahianna The changes that we discussed yesterday has been uploaded. If this looks good, you can go ahead and approve it

**Review by Dahianna — APPROVED** [review]

**Pull request merged**
